import React from 'react';
import { Link } from 'react-router-dom';
import { APP_NAME, SUPPORT_EMAIL, PAGES } from '../../types';
import LegalPageLayout from './LegalPageLayout';

const TermsOfService: React.FC = () => {
  return (
    <LegalPageLayout title="Terms of Service" lastUpdated="February 20, 2026" pageNameKey="TERMS_OF_SERVICE">
      <h3>1. Acceptance of Terms</h3>
      <p>
        By accessing or using {APP_NAME} ("the Service"), you agree to be bound by these Terms of Service ("Terms").
        If you do not agree to these Terms, you may not use the Service. Your continued use of the Service after
        any changes to these Terms constitutes your acceptance of the revised Terms.
      </p>

      <h3>2. Service Description</h3>
      <p>
        {APP_NAME} is an AI-powered credit card recommendation platform that helps users optimize their credit card
        usage. The Service provides personalized card recommendations, credit and benefit tracking, and portfolio
        management tools.
      </p>
      <p>
        {APP_NAME} is <strong>not a financial institution</strong>, bank, credit card issuer, or licensed financial
        advisor. We do not issue credit cards, process payments, or have access to your financial accounts.
      </p>

      <h3>3. Beta Disclaimer</h3>
      <div className="callout callout--warning">
        <p>
          <strong>The Service is currently in beta.</strong> Features may change, be removed, or experience issues
          without advance notice. There is no guaranteed uptime or availability during the beta period.
        </p>
      </div>
      <p>
        By using the Service during the beta period, you acknowledge that you may encounter bugs, incomplete
        features, or other issues. We appreciate your feedback and patience as we continue to develop the platform.
      </p>

      <h3>4. AI-Generated Content Disclaimer</h3>
      <div className="callout callout--warning">
        <p>
          <strong>The recommendations provided by {APP_NAME} are generated by artificial intelligence and are for
          informational purposes only.</strong> They do not constitute financial advice, investment advice, or any
          other form of professional advice.
        </p>
      </div>
      <p>
        To generate recommendations, your chat messages, card portfolio data (including card names, annual fees,
        earning rates, and credit balances), and display name are sent to third-party AI providers for processing.
        See our <Link to={PAGES.PRIVACY_POLICY.PATH}>Privacy Policy</Link> for details on which providers receive
        your data.
      </p>
      <p>
        AI-generated recommendations may contain inaccuracies, outdated information, or errors. Credit card terms,
        rewards rates, and benefits change frequently and may not be reflected in real time. You should always verify
        information directly with your card issuer before making financial decisions.
      </p>
      <p>
        {APP_NAME} is not responsible for any financial decisions you make based on the information provided through
        the Service.
      </p>

      <h3>5. Eligibility</h3>
      <p>
        You must be at least 18 years of age to use the Service. By using {APP_NAME}, you represent and warrant that
        you meet this age requirement and have the legal capacity to enter into these Terms.
      </p>

      <h3>6. User Accounts</h3>
      <p>
        To use the Service, you must create an account. You are responsible for:
      </p>
      <ul>
        <li>Maintaining the confidentiality of your account credentials</li>
        <li>All activity that occurs under your account</li>
        <li>Providing accurate and up-to-date information</li>
        <li>Notifying us promptly of any unauthorized use of your account</li>
      </ul>
      <p>
        Each person may maintain only one account. We reserve the right to suspend or terminate duplicate accounts.
      </p>

      <h3>7. Acceptable Use</h3>
      <p>
        You agree not to:
      </p>
      <ul>
        <li>Use the Service for any unlawful purpose or in violation of any applicable laws</li>
        <li>Attempt to gain unauthorized access to the Service or its systems</li>
        <li>Scrape, crawl, or use automated tools to extract data from the Service</li>
        <li>Interfere with or disrupt the Service or its infrastructure</li>
        <li>Impersonate another person or entity</li>
        <li>Use the Service to transmit spam, malware, or other harmful content</li>
        <li>Reverse engineer, decompile, or disassemble any part of the Service</li>
        <li>Share your account credentials with others or allow others to access your account</li>
      </ul>

      <h3>8. Intellectual Property</h3>
      <p>
        The Service, including its design, features, content, and underlying technology, is owned by {APP_NAME} and
        is protected by intellectual property laws. You may not copy, modify, distribute, or create derivative works
        from any part of the Service without our express written permission.
      </p>
      <p>
        You retain ownership of any data you provide to the Service, including your card selections, preferences,
        and chat inputs. By using the Service, you grant us a limited license to use this data to provide and improve
        the Service, including processing through third-party AI services as described in
        our <Link to={PAGES.PRIVACY_POLICY.PATH}>Privacy Policy</Link>. We will not sell your data or use it to train
        machine learning models independent of providing the Service to you.
      </p>

      <h3>9. Limitation of Liability</h3>
      <p>
        The Service is provided <strong>"as is" and "as available"</strong> without warranties of any kind, whether
        express or implied, including but not limited to warranties of merchantability, fitness for a particular
        purpose, or non-infringement. The Service may be unavailable from time to time due to maintenance, updates,
        or circumstances beyond our control.
      </p>
      <p>
        To the maximum extent permitted by law, {APP_NAME} and its operators shall not be liable for any indirect,
        incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data,
        or other intangible losses, arising from your use of or inability to use the Service.
      </p>
      <p>
        Our total aggregate liability to you for all claims arising from the Service shall not exceed the total fees
        you paid us in the twelve (12) months preceding the claim, or ten dollars ($10), whichever is greater.
      </p>
      <p>
        These Terms are governed by the laws of the State of Delaware. Any legal action arising from these Terms shall
        be brought exclusively in the state or federal courts located in Delaware, and you consent to the personal
        jurisdiction of such courts.
      </p>

      <h3>10. Account Termination</h3>
      <p>
        We reserve the right to suspend or terminate your account at any time for conduct that we determine violates
        these Terms, is harmful to other users, or is otherwise inappropriate. We will make reasonable efforts to
        notify you via email before terminating your account. Where the violation is not severe (such as fraud or
        abuse), we will provide a 14-day notice period to cure the issue before termination. If we terminate your
        account, your data will be deleted in accordance with
        our <Link to={PAGES.PRIVACY_POLICY.PATH}>Privacy Policy</Link>.
      </p>
      <p>
        You may delete your account at any time through the{' '}
        <Link to={PAGES.DELETE_ACCOUNT.PATH}>account deletion</Link> page. Upon deletion, your data will be
        permanently removed in accordance with our{' '}
        <Link to={PAGES.PRIVACY_POLICY.PATH}>Privacy Policy</Link>.
      </p>

      <h3>11. Changes to Terms</h3>
      <p>
        We may update these Terms from time to time. We will notify users of material changes by email and by
        updating the "Last updated" date at the top of this page. Material changes will take effect 30 days after
        notification. Your continued use of the Service after the 30-day notice period constitutes acceptance of the
        revised Terms. If you do not agree to the changes, you may delete your account before they take effect.
      </p>

      <h3>12. Indemnification</h3>
      <p>
        You agree to indemnify and hold harmless {APP_NAME} and its operators from any claims, damages, or expenses
        (including reasonable attorney fees) arising from your use of the Service, your violation of these Terms, or
        your violation of any third party's rights.
      </p>

      <h3>13. Contact Information</h3>
      <p>
        If you have questions about these Terms of Service, please contact us at{' '}
        <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.
      </p>
    </LegalPageLayout>
  );
};

export default TermsOfService;
